name: valid_doc
description: Check your document valid

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - files/passport.png
    - files/ident.png
    - files/car_id.png
    - files/visa.png
    - files/flags/brazil.png
    - files/flags/usa.png
    - files/flags/spain.png
    - files/flags/israel.png
    - files/flags/canada.png
    - files/flags/france.png
    - files/flags/italy.png
    - files/flags/portugal.png
    - files/flags/argentina.png
    - files/flags/peru.png
    - files/flags/chile.png
    - files/flags/poland.png
    - files/flags/uruguay.png
    - files/flags/colombia.png
    - files/flags/japan.png
    - files/flags/russia.png
    - files/flags/england.png
    - files/flags/germany.png
    - files/flags/australia.png
    - files/flags/china.png
    - files/flags/mexico.png
    - files/flags/paraguay.png

  fonts:
    - family: RobotoRegular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: QuicksandBold
      fonts:
        - asset: fonts/Quicksand-Bold.ttf
    - family: QuicksandLight
      fonts:
        - asset: fonts/Quicksand-Light.ttf
    - family: RobotoMedium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: TitilliumWebLight
      fonts:
        - asset: fonts/TitilliumWeb-Light.ttf
